version: "3"

services:
    app:
        build: ./docker/app
        volumes:
            - .:/workspace
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        environment:
            - TZ = "Asia/Tokyo"
        ports:
            - 8080:80
